-- --SECOND HIGHT SALARY KOTO & K PY

SELECT *
FROM EMPLOYEES
WHERE SALARY =(SELECT MAX(SALARY)
                FROM EMPLOYEES
                WHERE SLALRY < (SELECT MAX(SALARY)
                                FROM EMPLOYEES
                                )
                );

-- KON KON EMPLOYEES TADER MANAGER ER TAKHE BASHI SALARY PY

SELECT *
FROM EMPLOYEES AS EMP
WHERE SALARY > (SELECT SALARY
                FROM EMPLOYEES AS MGR
                WHERE EMP.MANAGER_ID = MGR.EMPLOYEES_ID
                );

-- KON KON EMPLOYEES TADER MANAGER ER MOTO SAME JOB KORE
SELECT *
FROM EMPLOYEES AS EMP
WHERE JOB_ID = (SELECT JOB_ID
                FROM EMPLOYEES AS MGR
                WHERE EMP.MANAGER_ID = MGR.EMPLOYEES_ID
                );

